"""empty message

Revision ID: 8c0c6323a732
Revises: 9b6497ded32f
Create Date: 2024-01-21 17:45:48.053423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c0c6323a732'
down_revision = '9b6497ded32f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detection_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('result', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detection_result', schema=None) as batch_op:
        batch_op.drop_column('result')

    # ### end Alembic commands ###
